const colors = require('./colors')

module.exports = {
    content: ["./dist/**/*.{html,js}"],
    theme: {
      colors: {
        // Build your palette here
        transparent: 'transparent',
        current: 'currentColor',
        white: colors.white,
        black: colors.black,
        gray: colors.gray,
        bluegray:colors.slate , 
        red: colors.red,
        blue: colors.blue,
        yellow: colors.amber,
        brown: colors.stone, 
        orange: colors.orange,
        green: colors.green , 
        lime: colors.lime ,
        teal: colors.teal , 
        indigo: colors.indigo,
        purple: colors.purple ,
        pink: colors.pink
    },
      extend: {
        width: {
          '72' : '18rem',
          '80' : '20rem',
          '96' : '24rem',
          '1/5': '20vw',
          '1/4': '25vw',
          '1/3': '33vw',
          '2/5': '40vw',
          '1/2': '50vw',
          '2/3': '66vw',
          '3/5': '60vw',
          '3/4': '75vw',
          '4/5': '80vw',
          '85' : '85vw',
          '90' : '90vw',
          '95' : '95vw',
          'none' : '0px',
          'px' : '1px',
          'full' : '100%',
          'screen' : '100vw',
          'min' : 'min-content',
          'max' : 'max-content',
          'prose' : '65ch',
          'xs' : '20rem',
          'sm' : '24rem',
          'md' : '28rem',
          'lg' : '32rem',
          'xl' : '36rem',
          '2xl' : '42rem',
          '3xl' : '48rem',
          'screen-sm' : '640px',
          'screen-md' : '768px',
          'screen-lg' : '1024px',
          'screen-xl' : '1280px',
          'screen-2xl' : '1536px',
          '11/12' : '91.66%',
          '4rem' : '4rem',
          '60px' : '60px'
        },
        height: {
          '72' : '18rem',
          '80' : '20rem',
          '96' : '24rem',
          '1/5': '20vh',
          '1/4': '25vh',
          '1/3': '33vh',
          '2/5': '40vh',
          '1/2': '50vh',
          '2/3': '66vh',
          '3/5': '60vh',
          '3/4': '75vh',
          '4/5': '80vh',
          '85' : '85vh',
          '90' : '90vh',
          '95' : '95vh',
          'none' : '0px',
          'px' : '1px',
          'full' : '100%',
          'screen' : '100vh',
          'min' : 'min-content',
          'max' : 'max-content',
          'prose' : '65ch',
          'xs' : '20rem',
          'sm' : '24rem',
          'md' : '28rem',
          'lg' : '32rem',
          'xl' : '36rem',
          '2xl' : '42rem',
          '3xl' : '48rem',
          'screen-sm' : '640px',
          'screen-md' : '768px',
          'screen-lg' : '1024px',
          'screen-xl' : '1280px',
          'screen-2xl' : '1536px',
          '11/12' : '91.66%',
          '4rem' : '4rem',
          '60px' : '60px'
        },
      },
      
    },
    plugins: [
    ],
  }